
services: 
  web: 
    build: .
    volumes: 
      - ./templates/static:/app/templates/static 
      - ./media:/app/media
    expose: 
      - 8000
  
  nginx: 
    image: nginx:alpine
    ports: 
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./templates/static:/app/templates/static
      - ./media:/app/media
    depends_on:
      - web
