# Nginx file to use inside docker-compose service.
# 
# 
# 
# 

server {
    listen 80;
    listen [::]:80;
    server_name localhost .onrender.com;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        # set to http://web:8000 to use inside the docker-compose service
        # otherwise, set to your app url (http://public-domain:public-port)
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server; 
    server_name _;

    location / {
        return 404 "Fallback: Page not found\n";
    }

    # You may need this to prevent 404 recursion
    location = /404.html {
        internal; 
    }
}