[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=2

[program:gunicorn]
command=gunicorn home.wsgi:application --bind 0.0.0.0:8000
directory=/app
autostart=true
autorestart=true
priority=1
