# Generated by Django 5.1.7 on 2025-04-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0006_reuniao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=255)),
                ('realizada', models.BooleanField(default=False)),
                ('mentorado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentorados.mentorados')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='mentorados/videos/')),
                ('mentorado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentorados.mentorados')),
            ],
        ),
    ]
